In [1]:
import pandas as pd

In [5]:
file_path = "/home/maaz-rafiq/work/phd_thesis_tanveer/CamelMedAgents-RAG/medical_parameter_extraction_pipeline/structured_queries_symptoms.jsonl"
file_path_org = "/home/maaz-rafiq/work/phd_thesis_tanveer/CamelMedAgents-RAG/medical_parameter_extraction_pipeline/structured_queries-org.jsonl"

In [6]:
df = pd.read_json(file_path, lines=True)
df

,original_text,label,category,symptoms
0,can someone help?! I've had bumps like this of...,acne,Dermatology,"[{'name': 'bumps', 'normalized_name': 'bumps',..."
1,I started getting acne since the age of 14 (I'...,acne,Dermatology,"[{'name': 'big, painful and red acne', 'normal..."
2,So i've been breaking out badly lately. I want...,acne,Dermatology,"[{'name': 'breaking out badly', 'normalized_na..."
3,"16 year old kid, about 3 years ago he was give...",acne,Dermatology,"[{'name': 'very red cheeks', 'normalized_name'..."
4,Been breaking out a lot due to this lockdown. ...,acne,Dermatology,"[{'name': 'breaking out', 'normalized_name': '..."
...,...,...,...,...
9056,I have a recurring UTI now for 5-6 months. I'm...,Urinary Tract Infection,Infectious Diseases,"[{'name': 'feeling worse', 'normalized_name': ..."
9057,Hey I am 9 weeks and 5 days pregnant have bad ...,Urinary Tract Infection,Infectious Diseases,"[{'name': 'bad urine infection', 'normalized_n..."
9058,"I've found a solution to my hives, and I just ...",Urticarial Rash,Dermatology,"[{'name': 'hives', 'normalized_name': 'hives',..."
9059,"Hey everyone, my heart goes out to all you suf...",Urticarial Rash,Dermatology,"[{'name': 'acid reflux', 'normalized_name': 'a..."
9060,"Hi everyone,My mother has recently started wan...",Alzheimer,Neurology,"[{'name': 'wandering off', 'normalized_name': ..."

In [7]:
df_org = pd.read_json(file_path_org, lines=True)
df_org

,symptoms,duration,severity_overall,anatomical_locations,demographics,intent,red_flag,comorbidities,query_complexity_score,original_text,label,category
0,"[{'name': 'bumps', 'anatomical_location': '', ...","{'value': 'a couple months', 'normalized_days'...",,[],"{'age': None, 'age_group': '', 'gender': '', '...",diagnosis,False,[],1,can someone help?! I've had bumps like this of...,acne,Dermatology
1,"[{'name': 'acne', 'anatomical_location': 'face...","{'value': '6 years', 'normalized_days': 2190, ...",severe,[face],"{'age': 20, 'age_group': 'adult', 'gender': ''...",treatment,False,[],3,I started getting acne since the age of 14 (I'...,acne,Dermatology
2,"[{'name': 'acne', 'anatomical_location': 'skin...","{'value': 'lately', 'normalized_days': 14, 'on...",moderate,[skin],"{'age': None, 'age_group': '', 'gender': '', '...",treatment,False,[],1,So i've been breaking out badly lately. I want...,acne,Dermatology
3,"[{'name': 'red cheeks', 'anatomical_location':...","{'value': '3 years', 'normalized_days': 1095, ...",,"[cheeks, chin, between eyebrows]","{'age': 16, 'age_group': 'adolescent', 'gender...",diagnosis,False,[],5,"16 year old kid, about 3 years ago he was give...",acne,Dermatology
4,"[{'name': 'acne', 'anatomical_location': 'skin...","{'value': '', 'normalized_days': 0, 'onset_typ...",,[skin],"{'age': None, 'age_group': '', 'gender': '', '...",treatment,False,[],1,Been breaking out a lot due to this lockdown. ...,acne,Dermatology
...,...,...,...,...,...,...,...,...,...,...,...,...
2971,"[{'name': 'floaters', 'anatomical_location': '...","{'value': '1.5 years', 'normalized_days': 547,...",severe,"[right eye, left eye]","{'age': None, 'age_group': '', 'gender': '', '...",treatment,False,[],3,I had 2 tears. I woke up with thousand small b...,Conjunctivitis,Ophthalmology
2972,"[{'name': 'vertical double vision', 'anatomica...","{'value': 'recently', 'normalized_days': 0, 'o...",,[eyes],"{'age': None, 'age_group': '', 'gender': '', '...",diagnosis,False,[astigmatism],3,"Hi all,So recently I’ve noticed I’ve had some ...",Conjunctivitis,Ophthalmology
2973,"[{'name': 'eye burning', 'anatomical_location'...","{'value': '', 'normalized_days': 0, 'onset_typ...",,[eye],"{'age': None, 'age_group': 'teenager', 'gender...",treatment,False,[],2,I use preservative free eye drops almost every...,Conjunctivitis,Ophthalmology
2974,"[{'name': 'red eye', 'anatomical_location': 'e...","{'value': 'last few days', 'normalized_days': ...",,[eye],"{'age': 22, 'age_group': 'adult', 'gender': ''...",diagnosis,False,[high cholesterol],1,I am 22. The white part of my eye is red since...,Conjunctivitis,Ophthalmology
2975,[],"{'value': '5 days', 'normalized_days': 5, 'ons...",,[right eye],"{'age': None, 'age_group': '', 'gender': '', '...",reassurance,False,"[cataract, gallbladder issues]",0,I had right eye cataract surgery 5 days ago. L...,Conjunctivitis,Ophthalmology

In [34]:
# df = df.rename(columns={"symptoms": "symptoms_df"})
df_org = df_org.rename(columns={"symptoms": "symptoms_org"})

In [35]:
df_merge = pd.merge(df, df_org, on="original_text", how="inner")
df_merge = df_merge[["original_text", "symptoms", "symptoms_org"]]
df_merge

,original_text,symptoms,symptoms_org
0,can someone help?! I've had bumps like this of...,"[{'name': 'bumps', 'normalized_name': None, 'a...","[{'name': 'bumps', 'anatomical_location': '', ..."
1,I started getting acne since the age of 14 (I'...,"[{'name': 'acne', 'normalized_name': None, 'an...","[{'name': 'acne', 'anatomical_location': 'face..."
2,So i've been breaking out badly lately. I want...,"[{'name': 'acne', 'normalized_name': None, 'an...","[{'name': 'acne', 'anatomical_location': 'skin..."
3,"16 year old kid, about 3 years ago he was give...","[{'name': 'redness', 'normalized_name': None, ...","[{'name': 'red cheeks', 'anatomical_location':..."
4,Been breaking out a lot due to this lockdown. ...,"[{'name': 'acne', 'normalized_name': None, 'an...","[{'name': 'acne', 'anatomical_location': 'skin..."
...,...,...,...
946,I was diagnosed with low B12 levels and furthe...,"[{'name': 'vague feeling', 'normalized_name': ...","[{'name': 'vague feeling', 'anatomical_locatio..."
947,Earlier this year I was diagnosed with b12 def...,"[{'name': 'memory loss', 'normalized_name': No...","[{'name': 'memory loss', 'anatomical_location'..."
948,I'm b12 deficiency. I was diagnosed with vitam...,"[{'name': 'sore tongue', 'normalized_name': No...","[{'name': 'sore tongue', 'anatomical_location'..."
949,Hello there I am booked in to have my first B1...,"[{'name': 'pins and needles', 'normalized_name...","[{'name': 'paresthesia', 'anatomical_location'..."
950,I have been going to my docs for over a year w...,"[{'name': 'headaches', 'normalized_name': None...","[{'name': 'headaches', 'anatomical_location': ..."

In [36]:
df_merge.to_csv("/home/maaz-rafiq/work/phd_thesis_tanveer/CamelMedAgents-RAG/dataset/merged_results_symptoms.csv", index=False)

In [8]:
df_org = df_org[['original_text','symptoms']]
df_org.to_csv("/home/maaz-rafiq/work/phd_thesis_tanveer/CamelMedAgents-RAG/dataset/symptoms_org.csv", index=False)

In [7]:
df = df[['original_text','symptoms']]
df.to_csv("/home/maaz-rafiq/work/phd_thesis_tanveer/CamelMedAgents-RAG/dataset/symptoms.csv", index=False)

In [ ]:
df = pd.read_json(file_path, lines=True)

In [ ]:
len(df.severity_overall)

831

In [9]:
file_path = "/home/maaz-rafiq/work/phd_thesis_tanveer/CamelMedAgents-RAG/medical_parameter_extraction_pipeline/structured_queries_symptoms.jsonl"

data = []

with open(file_path, "r", encoding="utf-8") as f:
    for line in f:
        data.append(line)

print(data)

['{"original_text": "can someone help?! I\'ve had bumps like this off and on for a couple months now and I\'m not sure if I am having an allergic reaction to something or if I\'m starting to get acne. Any advice is appreciated!", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "bumps", "normalized_name": "bumps", "anatomical_location": "", "severity": ""}]}\n', '{"original_text": "I started getting acne since the age of 14 (I\'m 20 now). sometimes it is severe and sometimes it clears out completely. from the past 2 weeks i\'m having severe acne. it is big, painful and red. I don\'t know what type of acne this is. can someone tell me what i should do to clear this.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "big, painful and red acne", "normalized_name": "acne lesions", "anatomical_location": "", "severity": "severe"}]}\n', '{"original_text": "So i\'ve been breaking out badly lately. I want to try some home remedies, i saw that using colgate and vaseline could help. Has anyone tried this? If so, how did it work for you?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "breaking out badly", "normalized_name": "acne lesions", "anatomical_location": "", "severity": "severe"}]}\n', '{"original_text": "16 year old kid, about 3 years ago he was given some prescribed acne meds by his doctor. Now, he has very red cheeks, it looks like he\'s constantly blushing, and generally red skin on his chin and between his eyebrows. Along with that, he tends to get pimples (some blackheads, some inflamed whiteheads) on his chin, in the same general area as the redness on his chin. The acne meds don\'t seem to be helping too much, it\'s just a twice daily face wash and clindamycin phosphate topical lotion. Haven\'t been to the doctor\'s recently, not sure if I even want to take him with all that\'s going on. He\'s never had acne on his cheeks where that red is, yet nothing seems to help. Wondering whether anyone might have any ideas as to if the acne meds could be worsening the redness if it is rosacea, or if something stronger is needed if it\'s acne. Thanks for any help!", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "very red cheeks", "normalized_name": "redness", "anatomical_location": "cheeks", "severity": ""}, {"name": "red skin on his chin", "normalized_name": "redness", "anatomical_location": "chin", "severity": ""}, {"name": "red skin between his eyebrows", "normalized_name": "redness", "anatomical_location": "between eyebrows", "severity": ""}, {"name": "pimples on his chin", "normalized_name": "acne lesions", "anatomical_location": "chin", "severity": ""}]}\n', '{"original_text": "Been breaking out a lot due to this lockdown. Anyone have any at-home remedies that i can try?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "breaking out", "normalized_name": "acne lesions", "anatomical_location": "", "severity": ""}]}\n', '{"original_text": "Maybe I am being too hopeful here but I would like to know if there are other treatments for Acne which is nodular and cystic/boils, other than Isotretinoin and all its variant names.I\'ve been given 10mg starting dose of the drug by my Dermatologist a few weeks ago but I haven\'t taken it mostly because I worry about the side effects. I will be having a consultation soon with them on the phone and wonder how to explain to them why I haven\'t taken it so they will understand.I\'ve been through a difficult time right now being stressed often with low mood, and been more anxious since the current events. And I thought taking this particular drug at this time would be a extra weight on my shoulders monitoring for side effects and I have dry skin already from eczema so taking this drug has been such a dilemma for me.I\'ve suffered from bad acne suddenly since August last year. It is localised mostly on my face and cheeks but particularly bad on my neck and I\'ve got scars from it. I took Lymecycline for a few months but it made no difference, the same with an over-the-counter cream.I get consistent whiteheads forming in different locations on my face but the worst are the nodular ones which turn into boils on my neck and these are quite common..I know I\'ve been offered a treatment plan for it but as mentioned I am reluctant because of the side effects and my family think I should try everything before taking it.Are there other prescriptions such as topical Retinoids that could help, without serious potential side effects like Crohn\'s disease? What other treatments help? I\'ve consumed dairy products for many years without bad acne and eaten the same foods for many months so it isn\'t likely to be dietary. Or maybe it is more stress or hormone related. What should I say to my Dermatologist? He says things like the topical solutions won\'t help without explanation.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "dry skin", "normalized_name": "dry skin", "anatomical_location": "", "severity": ""}, {"name": "low mood", "normalized_name": "low mood", "anatomical_location": "", "severity": ""}, {"name": "anxious", "normalized_name": "anxiety", "anatomical_location": "", "severity": ""}, {"name": "whiteheads forming", "normalized_name": "whiteheads", "anatomical_location": "face", "severity": ""}, {"name": "nodular ones which turn into boils", "normalized_name": "nodular acne", "anatomical_location": "neck", "severity": ""}]}\n', '{"original_text": "I have been taking Isotretinoin (Roacccutane) for forty-four days now. I was first prescribed this medication on the 25th February, two months after my initial appointment with the dermatologist. So far, I have seen an improvement in my acne. My skin and scalp are very dry. There has been no change in my mood and I don\'t think I have any other side effects from taking it. Acne has affected my life for so long and I was happy that I was finally starting to see a change!The dermatologist was very reluctant to prescribe me the medication as the results of my initial blood test revealed I had high cholesterol. Never the less, I was initially prescribed Isotretinoin for 30 days (but was given 56 capsules) and would need a monthly review. I was due a second blood test on the 16th March and a follow up appointment on the 27th March, however due to coronavirus those appointments were cancelled and since then I have had radio silence from the dermatologist. With total appreciation and understanding of how busy everybody at the NHS is right now, I must admit that I do feel as if I have fallen through the net.Due to how serious this drug is I was told that I would need to be monitored on a monthly basis. That I would have been prescribed more medication depending on the results of my blood tests and how well I was reacting to the treatment. The dermatologist herself listed a whole bunch of scary side effects and I had to sign form to acknowledge this. So with that, I wonder how a patient taking a drug that is labelled with such adverse side effects can just be put aside and forgotten about. I have waited a long time to get this medication and it\'s also disappointing that the journey is about to come to an abrupt end just as I was starting to see results!I was just curious to know if anybody else has found themselves in this situation?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "skin and scalp are very dry", "normalized_name": "dry skin", "anatomical_location": "skin", "severity": ""}, {"name": "skin and scalp are very dry", "normalized_name": "dry scalp", "anatomical_location": "scalp", "severity": ""}]}\n', '{"original_text": "I am 2.5 weeks into my isotretinoin course (20mg daily), and have developed a weird rash on my hand. There are some other small patches on upper arms and shoulders too. Is this normal? What should I do to treat this? I have been using a small amount of 1% hydrocortisone on the patches and seems to be helping slightly. Is this safe and/or a good treatment? Cheers", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "weird rash on my hand", "normalized_name": "rash", "anatomical_location": "hand", "severity": ""}, {"name": "small patches on upper arms", "normalized_name": "rash", "anatomical_location": "upper arms", "severity": ""}, {"name": "small patches on shoulders", "normalized_name": "rash", "anatomical_location": "shoulders", "severity": ""}]}\n', '{"original_text": "I never used to suffer from severe acne like this as far as I can remember. I did get bad acne as a teenager but not red, cystic bunches like this. For several months I\'ve had on and off pimples or whiteheads, mostly being on my face. But now they are nodular and recently came in lumps especially on my neck. Most of my acne is on my face and neck but I get it on my shoulders and upper arms too.It did start to happen when I was running into financial difficulty looking for work, working a stressful job and thinking about rent payments. I suppose the cause is emotional. I\'m feeling better but the acne keeps coming back.My dermatologist suggested me to try Lymecycline antibiotic. I took the whole course but it didn\'t clear my acne. He then suggested I try Accutane on a low dose after noticing my lumps (not from these pictures though) I recently gave up a blood sample for it and seeing him mid March. I am nervous taking such a drug because of the reported effects and my eczema which has been better recently. My dermatologist really rushes through appointments and I\'m unable to get very detailed responses from him, probably as he\'s always really busy.Do you think its worth taking Accutane for cystic, tender acne like such? Or should I make a GP appointment to get another professional opinion?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "red, cystic bunches", "normalized_name": "cystic acne", "anatomical_location": "face", "severity": "severe"}, {"name": "pimples or whiteheads", "normalized_name": "acne lesions", "anatomical_location": "face", "severity": ""}, {"name": "nodular lumps", "normalized_name": "nodular acne", "anatomical_location": "neck", "severity": ""}, {"name": "acne", "normalized_name": "acne lesions", "anatomical_location": "shoulders", "severity": ""}, {"name": "acne", "normalized_name": "acne lesions", "anatomical_location": "upper arms", "severity": ""}, {"name": "tender acne", "normalized_name": "tender acne", "anatomical_location": "face", "severity": ""}]}\n', '{"original_text": "It used to itch a little bit when I was starting to notice it months ago. This never happened before but it\'s never gone away and it\'s progressively getting worse. Now it doesn\'t itch at all but has definitely gotten both bigger in size, not just overall radius, and has a brighter redness to it now as well. Yes I use soap and I scrub myself.I hope this isn\'t anything to worry about although for being married a year and a half and now this comes right out of the blue just after a couple suspicious behaviours are brought out from my wife, I do hope that this isn\'t meaning she\'s cheating such as with contracting an STD and then sharing it with me but as with no strong reason for suspicion as of yet, I still don\'t know if she is. I am hoping she is being honest but this does have me concerned about my health. (Pics below).Also, we are both 24 years old, this rash or whatever it is has only shown up on my butt and I have fairly good hygiene. My underwear is breathable and I never wear the same pair the next day. I\'m shocked thinking about it considering my family goes my entirely different standards.Thanks in advance", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "itch", "normalized_name": "itching", "anatomical_location": "butt", "severity": "mild"}, {"name": "bigger in size", "normalized_name": "swelling", "anatomical_location": "butt", "severity": ""}, {"name": "brighter redness", "normalized_name": "redness", "anatomical_location": "butt", "severity": ""}]}\n', '{"original_text": "i have never had a problem with acne. im 25 and im constantly getting acne on my jaw line and near my lips but not on my lips. does anyone know what could cause this? my diet hasnt changed. ", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "acne on my jaw line", "normalized_name": "acne lesions", "anatomical_location": "jaw line", "severity": ""}, {"name": "acne near my lips", "normalized_name": "acne lesions", "anatomical_location": "near lips", "severity": ""}]}\n', '{"original_text": "so i get spots if i shave with a razor and i can understand why. but its been many years that i am shaving with trimmer and yet i get spots!i have severe keratosis pilaris on my arms and i guess hey are on my face too because my face is very bumpy and every pore is blocked. i tried many ways suggested by here and many other places for unblocking pores, exfoliating and many more but they didn\'t help.also the hair on my face (full face, beard and everywhere else) comes off when i grip on it by nails. its like 1 hair is ok but another tiny hair is stuck on to the side of the other one, and that\'s what comes off.i see ppl shaving in the morning and leaving off to work but when i shave i have to go shower and wash my face a thousand times because those tiny hairs that get cut by the trimmers get very itchy so i cant say i left it on my face and caused a spot.any help? im just so tired of this situation", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "spots", "normalized_name": "acne lesions", "anatomical_location": "face", "severity": ""}, {"name": "bumpy face", "normalized_name": "skin bumps", "anatomical_location": "face", "severity": ""}, {"name": "blocked pores", "normalized_name": "clogged pores", "anatomical_location": "face", "severity": ""}, {"name": "itchy face", "normalized_name": "itching", "anatomical_location": "face", "severity": ""}]}\n', '{"original_text": "i was getting itchy on my butt cheek and been itching and not sure what these bumps are.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "itchy", "normalized_name": "itching", "anatomical_location": "butt cheek", "severity": ""}, {"name": "bumps", "normalized_name": "bumps", "anatomical_location": "butt cheek", "severity": ""}]}\n', '{"original_text": "I started suffering from chest and back acne from about the age of 39. I\'m now 41 and am still suffering. Have tried many over the counter treatments and keep my skin as clean as possible. It really affects my self confidence! Any advice would be appreciated. Thanks", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "chest and back acne", "normalized_name": "acne lesions", "anatomical_location": "chest", "severity": ""}, {"name": "chest and back acne", "normalized_name": "acne lesions", "anatomical_location": "back", "severity": ""}]}\n', '{"original_text": "Hello,Hope I post in the right place...(Pictures)https://www.dropbox.com/s/4xqfeyqviv26h09/79308007_456553608333211_1535580902879395840_n.jpg?dl=0https://www.dropbox.com/s/vl0fxwpwwa2rtt6/79107815_556636441834155_5880687737287213056_n.jpg?dl=0If anyone could help me it would be great. I have been to the doctors for this and they told me it was pilonidal sinus and that the only solution for this is surgery and it’s not 100% guaranteed that the problem will go away (Chance of it coming back).I am getting these spots/holes every week in the same area. The red spot/lump is on my right bum cheek right at the top where my ass crack starts (sorry for the language). It happens every week and it is always bursting with blood and blood clots.Then I have 3 holes on my ass crack near the top which is always giving out sticky pus and blood. I don’t know If it is related but my lower back is hurting very badly and so are my muscles in general. Can someone tell me exactly what it is and tell me some solution for this other than surgery. I would do surgery but the doctor says it’s not 100% guaranteed solution as they can always come back therefore I am looking for some other solution like maybe some anti-biotic or cream etc.Thank you.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "red spot/lump", "normalized_name": "lump", "anatomical_location": "right buttock", "severity": ""}, {"name": "bursting with blood and blood clots", "normalized_name": "bleeding", "anatomical_location": "right buttock", "severity": ""}, {"name": "sticky pus and blood", "normalized_name": "discharge", "anatomical_location": "top of buttock crack", "severity": ""}, {"name": "lower back is hurting very badly", "normalized_name": "lower back pain", "anatomical_location": "lower back", "severity": "very bad"}, {"name": "muscles in general are hurting", "normalized_name": "muscle pain", "anatomical_location": "", "severity": ""}]}\n', '{"original_text": "i\'ve had pretty much clear skin since january but about 2 weeks after moving to university my chin started looking like this? ive googled it and was thinking it could be perioral demermatitis but im not sure because thats normally caused me steroids? however i have been using a new toothpaste while at uni which could maybe have caused it? anyone know why this had happened and how i can treat it?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "chin started looking like this", "normalized_name": "acne lesions", "anatomical_location": "chin", "severity": ""}]}\n', '{"original_text": "I\'m 25 and always had fairly clear skin but about a year ago startes getting a few spots. As they began to get worse i started trying over the counter treatments but nothing worked. Saw a dermatologist a few months ago and she suggested a new skin regime but nothing has worked. Tried epiduo and duac and have now been given lymecycline to try as my skin is the worst it has ever been. It appears to get better for a few days then breaks out even worse. Has anyone had experiences with lymecycline or similar experiences and has any advice? Got to the point where I wont leave the house.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "spots", "normalized_name": "acne lesions", "anatomical_location": "skin", "severity": ""}, {"name": "breaks out", "normalized_name": "acne lesions", "anatomical_location": "skin", "severity": "worse"}]}\n', '{"original_text": "I have severe acne on my face from last 6 months. Even after consulting dermatologist, I\'m not getting results. Can anyone have any solution?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "acne on my face", "normalized_name": "acne lesions", "anatomical_location": "face", "severity": "severe"}]}\n', '{"original_text": "I made a huge mistake by picking at a black head and now the skin underneath has turned pink. Does it eventually fade away & turn back to my natural skin complexion?I’m also a fashion blogger so this is a huge inconvenience but I’ll be fine lol.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "skin underneath has turned pink", "normalized_name": "skin discoloration", "anatomical_location": "", "severity": ""}]}\n', '{"original_text": "Does anyone know what exactly this thing is? on top of my eyelid. it does not hurt nor discharge any fluid. ", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "thing on top of my eyelid", "normalized_name": "eyelid lesion", "anatomical_location": "eyelid", "severity": ""}]}\n', '{"original_text": "Hi everyone,I\'m a 19-year-old male and I\'ve been struggling with acne since I was about 16. When I was in high school, I used to get cystic acne on my checks and chin and papules on my forehead and cheeks, and whiteheads on my lips and nose FREQUENTLY. There was always at least one or two noticeable pimples on my face at all times. In the summer before leaving for college I broke out tremendously. I didnt want to leave the house. As the first week or two of college pa

In [10]:
f = open(file_path, 'r')
    # Parsing the JSON file into a Python dictionary
for line in f:
    print(line)

{"original_text": "can someone help?! I've had bumps like this off and on for a couple months now and I'm not sure if I am having an allergic reaction to something or if I'm starting to get acne. Any advice is appreciated!", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "bumps", "normalized_name": "bumps", "anatomical_location": "", "severity": ""}]}

{"original_text": "I started getting acne since the age of 14 (I'm 20 now). sometimes it is severe and sometimes it clears out completely. from the past 2 weeks i'm having severe acne. it is big, painful and red. I don't know what type of acne this is. can someone tell me what i should do to clear this.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "big, painful and red acne", "normalized_name": "acne lesions", "anatomical_location": "", "severity": "severe"}]}

{"original_text": "So i've been breaking out badly lately. I want to try some home remedies, i saw that using colgate and vaseline could help. Has anyone tried this? If so, how did it work for you?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "breaking out badly", "normalized_name": "acne lesions", "anatomical_location": "", "severity": "severe"}]}

{"original_text": "16 year old kid, about 3 years ago he was given some prescribed acne meds by his doctor. Now, he has very red cheeks, it looks like he's constantly blushing, and generally red skin on his chin and between his eyebrows. Along with that, he tends to get pimples (some blackheads, some inflamed whiteheads) on his chin, in the same general area as the redness on his chin. The acne meds don't seem to be helping too much, it's just a twice daily face wash and clindamycin phosphate topical lotion. Haven't been to the doctor's recently, not sure if I even want to take him with all that's going on. He's never had acne on his cheeks where that red is, yet nothing seems to help. Wondering whether anyone might have any ideas as to if the acne meds could be worsening the redness if it is rosacea, or if something stronger is needed if it's acne. Thanks for any help!", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "very red cheeks", "normalized_name": "redness", "anatomical_location": "cheeks", "severity": ""}, {"name": "red skin on his chin", "normalized_name": "redness", "anatomical_location": "chin", "severity": ""}, {"name": "red skin between his eyebrows", "normalized_name": "redness", "anatomical_location": "between eyebrows", "severity": ""}, {"name": "pimples on his chin", "normalized_name": "acne lesions", "anatomical_location": "chin", "severity": ""}]}

{"original_text": "Been breaking out a lot due to this lockdown. Anyone have any at-home remedies that i can try?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "breaking out", "normalized_name": "acne lesions", "anatomical_location": "", "severity": ""}]}

{"original_text": "Maybe I am being too hopeful here but I would like to know if there are other treatments for Acne which is nodular and cystic/boils, other than Isotretinoin and all its variant names.I've been given 10mg starting dose of the drug by my Dermatologist a few weeks ago but I haven't taken it mostly because I worry about the side effects. I will be having a consultation soon with them on the phone and wonder how to explain to them why I haven't taken it so they will understand.I've been through a difficult time right now being stressed often with low mood, and been more anxious since the current events. And I thought taking this particular drug at this time would be a extra weight on my shoulders monitoring for side effects and I have dry skin already from eczema so taking this drug has been such a dilemma for me.I've suffered from bad acne suddenly since August last year. It is localised mostly on my face and cheeks but particularly bad on my neck and I've got scars from it. I took Lymecycline for a few months but it made no difference, the same with an over-the-counter cream.I get consistent whiteheads forming in different locations on my face but the worst are the nodular ones which turn into boils on my neck and these are quite common..I know I've been offered a treatment plan for it but as mentioned I am reluctant because of the side effects and my family think I should try everything before taking it.Are there other prescriptions such as topical Retinoids that could help, without serious potential side effects like Crohn's disease? What other treatments help? I've consumed dairy products for many years without bad acne and eaten the same foods for many months so it isn't likely to be dietary. Or maybe it is more stress or hormone related. What should I say to my Dermatologist? He says things like the topical solutions won't help without explanation.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "dry skin", "normalized_name": "dry skin", "anatomical_location": "", "severity": ""}, {"name": "low mood", "normalized_name": "low mood", "anatomical_location": "", "severity": ""}, {"name": "anxious", "normalized_name": "anxiety", "anatomical_location": "", "severity": ""}, {"name": "whiteheads forming", "normalized_name": "whiteheads", "anatomical_location": "face", "severity": ""}, {"name": "nodular ones which turn into boils", "normalized_name": "nodular acne", "anatomical_location": "neck", "severity": ""}]}

{"original_text": "I have been taking Isotretinoin (Roacccutane) for forty-four days now. I was first prescribed this medication on the 25th February, two months after my initial appointment with the dermatologist. So far, I have seen an improvement in my acne. My skin and scalp are very dry. There has been no change in my mood and I don't think I have any other side effects from taking it. Acne has affected my life for so long and I was happy that I was finally starting to see a change!The dermatologist was very reluctant to prescribe me the medication as the results of my initial blood test revealed I had high cholesterol. Never the less, I was initially prescribed Isotretinoin for 30 days (but was given 56 capsules) and would need a monthly review. I was due a second blood test on the 16th March and a follow up appointment on the 27th March, however due to coronavirus those appointments were cancelled and since then I have had radio silence from the dermatologist. With total appreciation and understanding of how busy everybody at the NHS is right now, I must admit that I do feel as if I have fallen through the net.Due to how serious this drug is I was told that I would need to be monitored on a monthly basis. That I would have been prescribed more medication depending on the results of my blood tests and how well I was reacting to the treatment. The dermatologist herself listed a whole bunch of scary side effects and I had to sign form to acknowledge this. So with that, I wonder how a patient taking a drug that is labelled with such adverse side effects can just be put aside and forgotten about. I have waited a long time to get this medication and it's also disappointing that the journey is about to come to an abrupt end just as I was starting to see results!I was just curious to know if anybody else has found themselves in this situation?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "skin and scalp are very dry", "normalized_name": "dry skin", "anatomical_location": "skin", "severity": ""}, {"name": "skin and scalp are very dry", "normalized_name": "dry scalp", "anatomical_location": "scalp", "severity": ""}]}

{"original_text": "I am 2.5 weeks into my isotretinoin course (20mg daily), and have developed a weird rash on my hand. There are some other small patches on upper arms and shoulders too. Is this normal? What should I do to treat this? I have been using a small amount of 1% hydrocortisone on the patches and seems to be helping slightly. Is this safe and/or a good treatment? Cheers", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "weird rash on my hand", "normalized_name": "rash", "anatomical_location": "hand", "severity": ""}, {"name": "small patches on upper arms", "normalized_name": "rash", "anatomical_location": "upper arms", "severity": ""}, {"name": "small patches on shoulders", "normalized_name": "rash", "anatomical_location": "shoulders", "severity": ""}]}

{"original_text": "I never used to suffer from severe acne like this as far as I can remember. I did get bad acne as a teenager but not red, cystic bunches like this. For several months I've had on and off pimples or whiteheads, mostly being on my face. But now they are nodular and recently came in lumps especially on my neck. Most of my acne is on my face and neck but I get it on my shoulders and upper arms too.It did start to happen when I was running into financial difficulty looking for work, working a stressful job and thinking about rent payments. I suppose the cause is emotional. I'm feeling better but the acne keeps coming back.My dermatologist suggested me to try Lymecycline antibiotic. I took the whole course but it didn't clear my acne. He then suggested I try Accutane on a low dose after noticing my lumps (not from these pictures though) I recently gave up a blood sample for it and seeing him mid March. I am nervous taking such a drug because of the reported effects and my eczema which has been better recently. My dermatologist really rushes through appointments and I'm unable to get very detailed responses from him, probably as he's always really busy.Do you think its worth taking Accutane for cystic, tender acne like such? Or should I make a GP appointment to get another professional opinion?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "red, cystic bunches", "normalized_name": "cystic acne", "anatomical_location": "face", "severity": "severe"}, {"name": "pimples or whiteheads", "normalized_name": "acne lesions", "anatomical_location": "face", "severity": ""}, {"name": "nodular lumps", "normalized_name": "nodular acne", "anatomical_location": "neck", "severity": ""}, {"name": "acne", "normalized_name": "acne lesions", "anatomical_location": "shoulders", "severity": ""}, {"name": "acne", "normalized_name": "acne lesions", "anatomical_location": "upper arms", "severity": ""}, {"name": "tender acne", "normalized_name": "tender acne", "anatomical_location": "face", "severity": ""}]}

{"original_text": "It used to itch a little bit when I was starting to notice it months ago. This never happened before but it's never gone away and it's progressively getting worse. Now it doesn't itch at all but has definitely gotten both bigger in size, not just overall radius, and has a brighter redness to it now as well. Yes I use soap and I scrub myself.I hope this isn't anything to worry about although for being married a year and a half and now this comes right out of the blue just after a couple suspicious behaviours are brought out from my wife, I do hope that this isn't meaning she's cheating such as with contracting an STD and then sharing it with me but as with no strong reason for suspicion as of yet, I still don't know if she is. I am hoping she is being honest but this does have me concerned about my health. (Pics below).Also, we are both 24 years old, this rash or whatever it is has only shown up on my butt and I have fairly good hygiene. My underwear is breathable and I never wear the same pair the next day. I'm shocked thinking about it considering my family goes my entirely different standards.Thanks in advance", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "itch", "normalized_name": "itching", "anatomical_location": "butt", "severity": "mild"}, {"name": "bigger in size", "normalized_name": "swelling", "anatomical_location": "butt", "severity": ""}, {"name": "brighter redness", "normalized_name": "redness", "anatomical_location": "butt", "severity": ""}]}

{"original_text": "i have never had a problem with acne. im 25 and im constantly getting acne on my jaw line and near my lips but not on my lips. does anyone know what could cause this? my diet hasnt changed. ", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "acne on my jaw line", "normalized_name": "acne lesions", "anatomical_location": "jaw line", "severity": ""}, {"name": "acne near my lips", "normalized_name": "acne lesions", "anatomical_location": "near lips", "severity": ""}]}

{"original_text": "so i get spots if i shave with a razor and i can understand why. but its been many years that i am shaving with trimmer and yet i get spots!i have severe keratosis pilaris on my arms and i guess hey are on my face too because my face is very bumpy and every pore is blocked. i tried many ways suggested by here and many other places for unblocking pores, exfoliating and many more but they didn't help.also the hair on my face (full face, beard and everywhere else) comes off when i grip on it by nails. its like 1 hair is ok but another tiny hair is stuck on to the side of the other one, and that's what comes off.i see ppl shaving in the morning and leaving off to work but when i shave i have to go shower and wash my face a thousand times because those tiny hairs that get cut by the trimmers get very itchy so i cant say i left it on my face and caused a spot.any help? im just so tired of this situation", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "spots", "normalized_name": "acne lesions", "anatomical_location": "face", "severity": ""}, {"name": "bumpy face", "normalized_name": "skin bumps", "anatomical_location": "face", "severity": ""}, {"name": "blocked pores", "normalized_name": "clogged pores", "anatomical_location": "face", "severity": ""}, {"name": "itchy face", "normalized_name": "itching", "anatomical_location": "face", "severity": ""}]}

{"original_text": "i was getting itchy on my butt cheek and been itching and not sure what these bumps are.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "itchy", "normalized_name": "itching", "anatomical_location": "butt cheek", "severity": ""}, {"name": "bumps", "normalized_name": "bumps", "anatomical_location": "butt cheek", "severity": ""}]}

{"original_text": "I started suffering from chest and back acne from about the age of 39. I'm now 41 and am still suffering. Have tried many over the counter treatments and keep my skin as clean as possible. It really affects my self confidence! Any advice would be appreciated. Thanks", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "chest and back acne", "normalized_name": "acne lesions", "anatomical_location": "chest", "severity": ""}, {"name": "chest and back acne", "normalized_name": "acne lesions", "anatomical_location": "back", "severity": ""}]}

{"original_text": "Hello,Hope I post in the right place...(Pictures)https://www.dropbox.com/s/4xqfeyqviv26h09/79308007_456553608333211_1535580902879395840_n.jpg?dl=0https://www.dropbox.com/s/vl0fxwpwwa2rtt6/79107815_556636441834155_5880687737287213056_n.jpg?dl=0If anyone could help me it would be great. I have been to the doctors for this and they told me it was pilonidal sinus and that the only solution for this is surgery and it’s not 100% guaranteed that the problem will go away (Chance of it coming back).I am getting these spots/holes every week in the same area. The red spot/lump is on my right bum cheek right at the top where my ass crack starts (sorry for the language). It happens every week and it is always bursting with blood and blood clots.Then I have 3 holes on my ass crack near the top which is always giving out sticky pus and blood. I don’t know If it is related but my lower back is hurting very badly and so are my muscles in general. Can someone tell me exactly what it is and tell me some solution for this other than surgery. I would do surgery but the doctor says it’s not 100% guaranteed solution as they can always come back therefore I am looking for some other solution like maybe some anti-biotic or cream etc.Thank you.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "red spot/lump", "normalized_name": "lump", "anatomical_location": "right buttock", "severity": ""}, {"name": "bursting with blood and blood clots", "normalized_name": "bleeding", "anatomical_location": "right buttock", "severity": ""}, {"name": "sticky pus and blood", "normalized_name": "discharge", "anatomical_location": "top of buttock crack", "severity": ""}, {"name": "lower back is hurting very badly", "normalized_name": "lower back pain", "anatomical_location": "lower back", "severity": "very bad"}, {"name": "muscles in general are hurting", "normalized_name": "muscle pain", "anatomical_location": "", "severity": ""}]}

{"original_text": "i've had pretty much clear skin since january but about 2 weeks after moving to university my chin started looking like this? ive googled it and was thinking it could be perioral demermatitis but im not sure because thats normally caused me steroids? however i have been using a new toothpaste while at uni which could maybe have caused it? anyone know why this had happened and how i can treat it?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "chin started looking like this", "normalized_name": "acne lesions", "anatomical_location": "chin", "severity": ""}]}

{"original_text": "I'm 25 and always had fairly clear skin but about a year ago startes getting a few spots. As they began to get worse i started trying over the counter treatments but nothing worked. Saw a dermatologist a few months ago and she suggested a new skin regime but nothing has worked. Tried epiduo and duac and have now been given lymecycline to try as my skin is the worst it has ever been. It appears to get better for a few days then breaks out even worse. Has anyone had experiences with lymecycline or similar experiences and has any advice? Got to the point where I wont leave the house.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "spots", "normalized_name": "acne lesions", "anatomical_location": "skin", "severity": ""}, {"name": "breaks out", "normalized_name": "acne lesions", "anatomical_location": "skin", "severity": "worse"}]}

{"original_text": "I have severe acne on my face from last 6 months. Even after consulting dermatologist, I'm not getting results. Can anyone have any solution?", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "acne on my face", "normalized_name": "acne lesions", "anatomical_location": "face", "severity": "severe"}]}

{"original_text": "I made a huge mistake by picking at a black head and now the skin underneath has turned pink. Does it eventually fade away & turn back to my natural skin complexion?I’m also a fashion blogger so this is a huge inconvenience but I’ll be fine lol.", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "skin underneath has turned pink", "normalized_name": "skin discoloration", "anatomical_location": "", "severity": ""}]}

{"original_text": "Does anyone know what exactly this thing is? on top of my eyelid. it does not hurt nor discharge any fluid. ", "label": "acne", "category": "Dermatology", "symptoms": [{"name": "thing on top of my eyelid", "normalized_name": "eyelid lesion", "anatomical_location": "eyelid", "severity": ""}]}


In [5]:
f[0]

TypeError: '_io.TextIOWrapper' object is not subscriptable

_io.TextIOWrapper